---
# Source: isdargo/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isdargo-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: isdargo
    heritage: Helm
type: Opaque
data:
  accesskey: "spinnakeradmin"
  secretkey: "spinnakeradmin"
