---
# Source: isdargo/templates/forwarder/opsmx-agent-controller-auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: opsmx-agent-controller-auth
type: Opaque
data:
  authtoken: aEJ6Nk1QZHpDUGphYzZQZ0ZrT0Y=
