---
# Source: isdargo/templates/forwarder/opsmx-agent-controller-auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: opsmx-agent-controller-auth
type: Opaque
data:
  authtoken: NnpEMjNDQ1d0d2xMSVUyME1mWEk=
