---
# Source: isdargo/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isdargo-redis
  labels:
    app: redis
    chart: redis-10.5.3
    release: "isdargo"
    heritage: "Helm"
type: Opaque
data:
  redis-password: "password"
