---
# Source: isdargo/templates/carina/carina-manager-secret.yaml
apiVersion: v1
stringData:
  carina-manager.yaml: |    
    httpListenPort: 8091
    argoUpdateFrequencySeconds: 30 
    rbac:
      httpListenPort: 8092
    controller:
      url: 'http://opsmx-controller-controller1:9003'
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    platformServiceUrl: http://oes-platform:8095
    databases:
      audit:
        type: postgresql
        connectString: host=oes-db  user='postgres' password='networks123' database=auditdb
      platform:
        type: postgresql
        connectString: host=oes-db user='postgres' password='networks123' database=platformdb
    
kind: Secret
metadata:
  labels:
    app: oes
    component: carina
    heritage: "Helm"
    release: "isdargo"
    chart: "isdargo-4.1.11"
  name: oes-carina-config
