---
# Source: isdargo/templates/autoconfigure-carin-and-agent/autoconfigserviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isd-auto-configure-default
---
# Source: isdargo/templates/autoconfigure-carin-and-agent/autoconfigserviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isd-auto-configure-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: isd-auto-configure-default
  namespace: default
