---
# Source: isdargo/templates/secrets/opsmx-profile.yaml
apiVersion: v1
kind: Secret
metadata:
  name: opsmx-profile
stringData:
  cdIntegration: "false"
  sourceName: "argocd"
  opsmxIsdUrl: http://oes-gate:8084
  user: "admin"
