apiVersion: batch/v1
kind: Job
metadata:
  name: isdargo-generate-yamls
  labels:
    app: isdargo
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - args:
            - |-
              set +x

              source /repo/environment
              
              rm -rf /repo/environment

              chmod +x /repo/upgrade/generate/isdargo-generate-yamls.sh
                   
              export version="$version"

              export release="$release"

              ls  -ltra /repo/

              /repo/upgrade/generate/isdargo-generate-yamls.sh
          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          image: 'quay.io/opsmxpublic/helm-bash:v4'
          name: gen-yamls
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      initContainers:
        - args:
            - >-

              aws secretsmanager get-secret-value --secret-id isdsecrets --query SecretString --output text > /tmp/secret.json
              
              jq -r .gittoken /tmp/secret.json > /secrets/gittoken
              
              git clone https://"$username":"$(cat /secrets/gittoken)"@"$url" -b "$branch" /repo
               
              echo "export namespace=$namespace" > /repo/environment

              echo "export version=$version" >> /repo/environment

              echo "export release=$release" >> /repo/environment

              ls -ltra /repo
          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
            - secretRef:
                name: aws-creds
          image: quay.io/opsmxpublic/opsmx-custom-binaries:aws-jq-git-bash
          name: git-clone
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
            - mountPath: /secrets
              name: secret-volume
      restartPolicy: Never
      serviceAccountName: isd-install
      volumes:
        - emptyDir: {}
          name: repo-volume
        - emptyDir: {}
          name: secret-volume
