apiVersion: v1
kind: ServiceAccount
metadata:
  name: isd-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isd-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: isd-install
    namespace: isdargo #Please update the namespace accordingly
---

# for opa init container to use
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: isd-argo-pod-reader
  namespace: isdargo
rules:
- apiGroups: [""]
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isd-argo-pod-reader-binding
  namespace: isdargo
subjects:
- kind: ServiceAccount
  name: default
  namespace: isdargo
roleRef:
  kind: Role
  name: isd-argo-pod-reader
  apiGroup: rbac.authorization.k8s.io
