---
# Source: isdargo/templates/oes-autopilot/oes-autopilot-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: autopilot
    heritage: "Helm"
    release: "isdargo"
    chart: "isdargo-4.1.11"
  name: oes-autopilot
spec:
  type: LoadBalancer
  ports:
  - name: "cas-service"
    port: 8090
    targetPort: 8090
  - name: "monitoring-service"
    port: 9090
    targetPort: 9090
  selector:
    app: oes
    component: autopilot
