---
# Source: isdargo/templates/oes-autopilot/oes-autopilot-secret.yaml
apiVersion: v1
stringData:
  autopilot.properties: |
    # Enable Build Analysis
    build.analysis=false
    # DB configuration
    secret.datasource.username=encrypted:isdsecrets:dbusername
    secret.datasource.password=encrypted:isdsecrets:dbpassword
    secret.datasource.url=jdbc:postgresql://oes-db:5432/opsmx
    secret.platform.url=http://oes-platform:8095
    secret.ds.protocol=http://
    secret.ds.url=localhost:5005
    secret.dashboard.url=http://oes-dashboard:8094
    server.host.dns.name=http://localhost:8093/ui
    gate.url=http://oes-gate:8084
    
    #datascience configuration
    oes.datascience.baseUrl=http://oes-datascience:5005
    #build.analysis=false
    ds.async.flow=true
    
    
    #audit services
    secret.auditservice.enabled=true
    secret.auditservice.name=auditservice
    secret.auditservice.url=http://oes-audit-service:8097
    secret.auditclientservice.name=auditclientservice
    secret.auditclientservice.url=http://oes-audit-client:8098
    
    # Standard-error-path
    standardErrorCodes.filePath=/opsmx/conf/standard-error-code.csv
    
    #Enable this feature flag when any elasticsearch, prometheus or splunk accounts are configured through agent.
    #When monitoringtool.accountconfig.agent.enabled flag is true copy the 3 certificate files generated by the agent in the autopilot pod.
    monitoringtool.accountconfig.agent.enabled=true
    monitoringtool.accountconfig.agent.caCertfile=/opsmx/conf/controller/ca.crt
    monitoringtool.accountconfig.agent.certFile=/opsmx/conf/controller/tls.crt
    monitoringtool.accountconfig.agent.keyFile=/opsmx/conf/controller/tls.key
    
    #storage configuration
    storage.type =db_storage
    #storage.type =object_storage
    #storage.endpoint=http://isdargo-minio:9000
    #storage.accesskey = encrypted:isdsecrets:miniopassword
    #storage.secretkey = encrypted:isdsecrets:miniopassword
    #storage.region= us-east-1
    ds.seperate.service=true
    
    
    # Logging Level
    logging.level.com.opsmx.analytics=ERROR
    datasource.secretManagement.source = db
    
kind: Secret
metadata:
  name: oes-autopilot-config
  labels:
    app: oes
    component: autopilot
    heritage: "Helm"
    release: "isdargo"
    chart: "isdargo-4.1.11"
